seed: 42

data:
  months: 12

  TB_CLIENTES_CORE: 10000
  TB_PRODUCTOS_CAT: 50
  TB_MOV_FINANCIEROS: 500000
  TB_OBLIGACIONES: 30000
  TB_SUCURSALES_RED: 200
  TB_COMISIONES_LOG: 80000

output:
  path: "output"
